{
 "title": "Dotmakeup audiance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Followers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM followers;"
    }
   ]
  },
  {
   "title": "Followers' servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT host) FROM followers;"
    }
   ]
  },
  {
   "title": "Connections (Twitter <> Fedi)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cardinality(followings)) FROM followers;"
    }
   ]
  },
  {
   "title": "twitter users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM (SELECT unnest(followings) as follow FROM followers GROUP BY follow) AS f INNER JOIN twitter_users ON f.follow=twitter_users.id"
    }
   ]
  },
  {
   "title": "Connections (instagram <> fedi)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cardinality(followings_instagram)) FROM followers;"
    }
   ]
  },
  {
   "title": "Instagram users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM (SELECT unnest(followings_instagram) as follow FROM followers GROUP BY follow) AS f INNER JOIN instagram_users ON f.follow=instagram_users.id"
    }
   ]
  },
  {
   "title": "Most popular servers",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT '' as d, host, COUNT(*) FROM followers GROUP BY host ORDER BY count DESC LIMIT 80"
    }
   ]
  },
  {
   "title": "Most popular twitter accounts",
   "type": "table",
   "gridPos": { "h": 28, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), acct, cache['Description'] as bio, extradata['wikidata']['Description'] as description, bool_or(vipfollow) as vip FROM (SELECT unnest(followings) as follow, host='r.town' as vipfollow FROM followers) AS f INNER JOIN twitter_users ON f.follow=twitter_users.id GROUP BY acct, bio, description ORDER BY count DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Most popular instagram accounts",
   "type": "table",
   "gridPos": { "h": 28, "w": 11, "x": 11, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), acct, cache['Description'] as bio, extradata['wikidata']['Description'] as description, bool_or(vipfollow) as vip FROM (SELECT unnest(followings_instagram) as follow, host='r.town' as vipfollow FROM followers) AS f INNER JOIN instagram_users ON f.follow=instagram_users.id GROUP BY acct, bio, description ORDER BY count DESC;"
    }
   ]
  }
 ]
}