{
 "title": "Dotmakeup infra",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Crawling time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT extract(epoch from max(lastsync) - min(lastsync))/3600 FROM (SELECT unnest(followings) as follow FROM followers GROUP BY follow) AS f INNER JOIN twitter_users ON f.follow=twitter_users.id"
    }
   ]
  },
  {
   "title": "Twitter tweets success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(result)(increase(dotmakeup_api_called_count{api=\"twitter_tweet\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New tweets by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by(source)(rate(dotmakeup_twitter_new_tweets_count[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Twitter user calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(result)(increase(dotmakeup_api_called_count{api=\"twitter_account\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(result)(increase(dotmakeup_api_called_count{api=\"twitter_sidecar_timeline\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "top controller requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(4, sum by(http_route)(increase(http_server_request_duration_count[6m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nitter endpoint success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by(domain)(increase(dotmakeup_api_called_count{api=\"nitter\",success=\"true\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "asp errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (http_route, error_type, http_request_method)(increase(http_server_request_duration_count{http_response_status_code=\"500\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}